-- ============================================================================
-- OPT SaaS – Datos iniciales: Comunas de Chile
-- Script:  009_comunas_datos.sql
-- Fuente:  INE – División político-administrativa 2020 (346 comunas)
-- IDs:     Explícitos (IDENTITY_INSERT ON) para coincidir con
--          frontend/src/app/core/data/regiones-comunas.data.ts
-- Idempotente: solo inserta si la tabla está vacía.
-- ============================================================================

USE [dbOPT];
GO

IF EXISTS (SELECT 1 FROM [dbo].[OPT_Comuna])
BEGIN
    PRINT 'OPT_Comuna ya tiene datos — se omite la inserción.';
    -- Para re-ejecutar en ambiente de desarrollo, limpiar primero:
    -- DELETE FROM [dbo].[OPT_Cliente];   -- (quitar FK dependientes)
    -- DELETE FROM [dbo].[OPT_Comuna];
    -- DBCC CHECKIDENT('[dbo].[OPT_Comuna]', RESEED, 0);
END
ELSE
BEGIN
    SET IDENTITY_INSERT [dbo].[OPT_Comuna] ON;

    -- Se usa JOIN con OPT_Region por Codigo para obtener idRegion real,
    -- independiente del valor IDENTITY asignado al crear las regiones.
    INSERT INTO [dbo].[OPT_Comuna]
        ([idComuna], [idRegion], [Comuna], [CreatedBy])
    SELECT v.[idComuna], r.[idRegion], v.[Comuna], 'SYSTEM'
    FROM (VALUES
        -- ── XV Arica y Parinacota (1-4) ──────────────────────────────────
        ( 1,  'XV',  'Arica'),
        ( 2,  'XV',  'Camarones'),
        ( 3,  'XV',  'Putre'),
        ( 4,  'XV',  'General Lagos'),
        -- ── I Tarapacá (5-11) ────────────────────────────────────────────
        ( 5,  'I',   'Iquique'),
        ( 6,  'I',   'Alto Hospicio'),
        ( 7,  'I',   'Pozo Almonte'),
        ( 8,  'I',   'Camiña'),
        ( 9,  'I',   'Colchane'),
        (10,  'I',   'Huara'),
        (11,  'I',   'Pica'),
        -- ── II Antofagasta (12-20) ───────────────────────────────────────
        (12,  'II',  'Antofagasta'),
        (13,  'II',  'Mejillones'),
        (14,  'II',  'Sierra Gorda'),
        (15,  'II',  'Taltal'),
        (16,  'II',  'Calama'),
        (17,  'II',  'Ollagüe'),
        (18,  'II',  'San Pedro de Atacama'),
        (19,  'II',  'Tocopilla'),
        (20,  'II',  'María Elena'),
        -- ── III Atacama (21-29) ──────────────────────────────────────────
        (21,  'III', 'Copiapó'),
        (22,  'III', 'Caldera'),
        (23,  'III', 'Tierra Amarilla'),
        (24,  'III', 'Chañaral'),
        (25,  'III', 'Diego de Almagro'),
        (26,  'III', 'Vallenar'),
        (27,  'III', 'Alto del Carmen'),
        (28,  'III', 'Freirina'),
        (29,  'III', 'Huasco'),
        -- ── IV Coquimbo (30-44) ──────────────────────────────────────────
        (30,  'IV',  'La Serena'),
        (31,  'IV',  'Coquimbo'),
        (32,  'IV',  'Andacollo'),
        (33,  'IV',  'La Higuera'),
        (34,  'IV',  'Paiguano'),
        (35,  'IV',  'Vicuña'),
        (36,  'IV',  'Illapel'),
        (37,  'IV',  'Canela'),
        (38,  'IV',  'Los Vilos'),
        (39,  'IV',  'Salamanca'),
        (40,  'IV',  'Ovalle'),
        (41,  'IV',  'Combarbalá'),
        (42,  'IV',  'Monte Patria'),
        (43,  'IV',  'Punitaqui'),
        (44,  'IV',  'Río Hurtado'),
        -- ── V Valparaíso (45-82) ─────────────────────────────────────────
        (45,  'V',   'Valparaíso'),
        (46,  'V',   'Casablanca'),
        (47,  'V',   'Concón'),
        (48,  'V',   'Juan Fernández'),
        (49,  'V',   'Puchuncaví'),
        (50,  'V',   'Quintero'),
        (51,  'V',   'Viña del Mar'),
        (52,  'V',   'Isla de Pascua'),
        (53,  'V',   'Los Andes'),
        (54,  'V',   'Calle Larga'),
        (55,  'V',   'Rinconada'),
        (56,  'V',   'San Esteban'),
        (57,  'V',   'La Ligua'),
        (58,  'V',   'Cabildo'),
        (59,  'V',   'Papudo'),
        (60,  'V',   'Petorca'),
        (61,  'V',   'Zapallar'),
        (62,  'V',   'Quillota'),
        (63,  'V',   'Calera'),
        (64,  'V',   'Hijuelas'),
        (65,  'V',   'La Cruz'),
        (66,  'V',   'Nogales'),
        (67,  'V',   'San Antonio'),
        (68,  'V',   'Algarrobo'),
        (69,  'V',   'Cartagena'),
        (70,  'V',   'El Quisco'),
        (71,  'V',   'El Tabo'),
        (72,  'V',   'Santo Domingo'),
        (73,  'V',   'San Felipe'),
        (74,  'V',   'Catemu'),
        (75,  'V',   'Llaillay'),
        (76,  'V',   'Panquehue'),
        (77,  'V',   'Putaendo'),
        (78,  'V',   'Santa María'),
        (79,  'V',   'Quilpué'),
        (80,  'V',   'Limache'),
        (81,  'V',   'Olmué'),
        (82,  'V',   'Villa Alemana'),
        -- ── RM Metropolitana de Santiago (83-134) ────────────────────────
        ( 83, 'RM',  'Santiago'),
        ( 84, 'RM',  'Cerrillos'),
        ( 85, 'RM',  'Cerro Navia'),
        ( 86, 'RM',  'Conchalí'),
        ( 87, 'RM',  'El Bosque'),
        ( 88, 'RM',  'Estación Central'),
        ( 89, 'RM',  'Huechuraba'),
        ( 90, 'RM',  'Independencia'),
        ( 91, 'RM',  'La Cisterna'),
        ( 92, 'RM',  'La Florida'),
        ( 93, 'RM',  'La Granja'),
        ( 94, 'RM',  'La Pintana'),
        ( 95, 'RM',  'La Reina'),
        ( 96, 'RM',  'Las Condes'),
        ( 97, 'RM',  'Lo Barnechea'),
        ( 98, 'RM',  'Lo Espejo'),
        ( 99, 'RM',  'Lo Prado'),
        (100, 'RM',  'Macul'),
        (101, 'RM',  'Maipú'),
        (102, 'RM',  'Ñuñoa'),
        (103, 'RM',  'Pedro Aguirre Cerda'),
        (104, 'RM',  'Peñalolén'),
        (105, 'RM',  'Providencia'),
        (106, 'RM',  'Pudahuel'),
        (107, 'RM',  'Quilicura'),
        (108, 'RM',  'Quinta Normal'),
        (109, 'RM',  'Recoleta'),
        (110, 'RM',  'Renca'),
        (111, 'RM',  'San Joaquín'),
        (112, 'RM',  'San Miguel'),
        (113, 'RM',  'San Ramón'),
        (114, 'RM',  'Vitacura'),
        (115, 'RM',  'Puente Alto'),
        (116, 'RM',  'Pirque'),
        (117, 'RM',  'San José de Maipo'),
        (118, 'RM',  'Colina'),
        (119, 'RM',  'Lampa'),
        (120, 'RM',  'Tiltil'),
        (121, 'RM',  'San Bernardo'),
        (122, 'RM',  'Buin'),
        (123, 'RM',  'Calera de Tango'),
        (124, 'RM',  'Paine'),
        (125, 'RM',  'Melipilla'),
        (126, 'RM',  'Alhué'),
        (127, 'RM',  'Curacaví'),
        (128, 'RM',  'María Pinto'),
        (129, 'RM',  'San Pedro'),
        (130, 'RM',  'Talagante'),
        (131, 'RM',  'El Monte'),
        (132, 'RM',  'Isla de Maipo'),
        (133, 'RM',  'Padre Hurtado'),
        (134, 'RM',  'Peñaflor'),
        -- ── VI O'Higgins (135-167) ───────────────────────────────────────
        (135, 'VI',  'Rancagua'),
        (136, 'VI',  'Codegua'),
        (137, 'VI',  'Coinco'),
        (138, 'VI',  'Coltauco'),
        (139, 'VI',  'Doñihue'),
        (140, 'VI',  'Graneros'),
        (141, 'VI',  'Las Cabras'),
        (142, 'VI',  'Machalí'),
        (143, 'VI',  'Malloa'),
        (144, 'VI',  'Mostazal'),
        (145, 'VI',  'Olivar'),
        (146, 'VI',  'Peumo'),
        (147, 'VI',  'Pichidegua'),
        (148, 'VI',  'Quinta de Tilcoco'),
        (149, 'VI',  'Rengo'),
        (150, 'VI',  'Requínoa'),
        (151, 'VI',  'San Vicente'),
        (152, 'VI',  'Pichilemu'),
        (153, 'VI',  'La Estrella'),
        (154, 'VI',  'Litueche'),
        (155, 'VI',  'Marchihue'),
        (156, 'VI',  'Navidad'),
        (157, 'VI',  'Paredones'),
        (158, 'VI',  'San Fernando'),
        (159, 'VI',  'Chépica'),
        (160, 'VI',  'Chimbarongo'),
        (161, 'VI',  'Lolol'),
        (162, 'VI',  'Nancagua'),
        (163, 'VI',  'Palmilla'),
        (164, 'VI',  'Peralillo'),
        (165, 'VI',  'Placilla'),
        (166, 'VI',  'Pumanque'),
        (167, 'VI',  'Santa Cruz'),
        -- ── VII Maule (168-197) ──────────────────────────────────────────
        (168, 'VII', 'Talca'),
        (169, 'VII', 'Constitución'),
        (170, 'VII', 'Curepto'),
        (171, 'VII', 'Empedrado'),
        (172, 'VII', 'Maule'),
        (173, 'VII', 'Pelarco'),
        (174, 'VII', 'Pencahue'),
        (175, 'VII', 'Río Claro'),
        (176, 'VII', 'San Clemente'),
        (177, 'VII', 'San Rafael'),
        (178, 'VII', 'Cauquenes'),
        (179, 'VII', 'Chanco'),
        (180, 'VII', 'Pelluhue'),
        (181, 'VII', 'Curicó'),
        (182, 'VII', 'Hualañé'),
        (183, 'VII', 'Licantén'),
        (184, 'VII', 'Molina'),
        (185, 'VII', 'Rauco'),
        (186, 'VII', 'Romeral'),
        (187, 'VII', 'Sagrada Familia'),
        (188, 'VII', 'Teno'),
        (189, 'VII', 'Vichuquén'),
        (190, 'VII', 'Linares'),
        (191, 'VII', 'Colbún'),
        (192, 'VII', 'Longaví'),
        (193, 'VII', 'Parral'),
        (194, 'VII', 'Retiro'),
        (195, 'VII', 'San Javier'),
        (196, 'VII', 'Villa Alegre'),
        (197, 'VII', 'Yerbas Buenas'),
        -- ── XVI Ñuble (198-218) ──────────────────────────────────────────
        (198, 'XVI', 'Chillán'),
        (199, 'XVI', 'Bulnes'),
        (200, 'XVI', 'Cobquecura'),
        (201, 'XVI', 'Coelemu'),
        (202, 'XVI', 'Coihueco'),
        (203, 'XVI', 'Chillán Viejo'),
        (204, 'XVI', 'El Carmen'),
        (205, 'XVI', 'Ninhue'),
        (206, 'XVI', 'Ñiquén'),
        (207, 'XVI', 'Pemuco'),
        (208, 'XVI', 'Pinto'),
        (209, 'XVI', 'Portezuelo'),
        (210, 'XVI', 'Quillón'),
        (211, 'XVI', 'Quirihue'),
        (212, 'XVI', 'Ránquil'),
        (213, 'XVI', 'San Carlos'),
        (214, 'XVI', 'San Fabián'),
        (215, 'XVI', 'San Ignacio'),
        (216, 'XVI', 'San Nicolás'),
        (217, 'XVI', 'Treguaco'),
        (218, 'XVI', 'Yungay'),
        -- ── VIII Biobío (219-250) ────────────────────────────────────────
        (219, 'VIII','Concepción'),
        (220, 'VIII','Coronel'),
        (221, 'VIII','Chiguayante'),
        (222, 'VIII','Florida'),
        (223, 'VIII','Hualpén'),
        (224, 'VIII','Hualqui'),
        (225, 'VIII','Lota'),
        (226, 'VIII','Penco'),
        (227, 'VIII','San Pedro de la Paz'),
        (228, 'VIII','Santa Juana'),
        (229, 'VIII','Talcahuano'),
        (230, 'VIII','Tomé'),
        (231, 'VIII','Cabrero'),
        (232, 'VIII','Laja'),
        (233, 'VIII','Los Ángeles'),
        (234, 'VIII','Mulchén'),
        (235, 'VIII','Nacimiento'),
        (236, 'VIII','Negrete'),
        (237, 'VIII','Quilaco'),
        (238, 'VIII','Quilleco'),
        (239, 'VIII','San Rosendo'),
        (240, 'VIII','Santa Bárbara'),
        (241, 'VIII','Tucapel'),
        (242, 'VIII','Yumbel'),
        (243, 'VIII','Alto Biobío'),
        (244, 'VIII','Arauco'),
        (245, 'VIII','Cañete'),
        (246, 'VIII','Contulmo'),
        (247, 'VIII','Curanilahue'),
        (248, 'VIII','Lebu'),
        (249, 'VIII','Los Álamos'),
        (250, 'VIII','Tirúa'),
        -- ── IX La Araucanía (251-282) ────────────────────────────────────
        (251, 'IX',  'Temuco'),
        (252, 'IX',  'Carahue'),
        (253, 'IX',  'Cunco'),
        (254, 'IX',  'Curarrehue'),
        (255, 'IX',  'Freire'),
        (256, 'IX',  'Galvarino'),
        (257, 'IX',  'Gorbea'),
        (258, 'IX',  'Lautaro'),
        (259, 'IX',  'Loncoche'),
        (260, 'IX',  'Melipeuco'),
        (261, 'IX',  'Nueva Imperial'),
        (262, 'IX',  'Padre Las Casas'),
        (263, 'IX',  'Perquenco'),
        (264, 'IX',  'Pitrufquén'),
        (265, 'IX',  'Pucón'),
        (266, 'IX',  'Saavedra'),
        (267, 'IX',  'Teodoro Schmidt'),
        (268, 'IX',  'Toltén'),
        (269, 'IX',  'Vilcún'),
        (270, 'IX',  'Villarrica'),
        (271, 'IX',  'Cholchol'),
        (272, 'IX',  'Angol'),
        (273, 'IX',  'Collipulli'),
        (274, 'IX',  'Curacautín'),
        (275, 'IX',  'Ercilla'),
        (276, 'IX',  'Lonquimay'),
        (277, 'IX',  'Los Sauces'),
        (278, 'IX',  'Lumaco'),
        (279, 'IX',  'Purén'),
        (280, 'IX',  'Renaico'),
        (281, 'IX',  'Traiguén'),
        (282, 'IX',  'Victoria'),
        -- ── XIV Los Ríos (283-294) ───────────────────────────────────────
        (283, 'XIV', 'Valdivia'),
        (284, 'XIV', 'Corral'),
        (285, 'XIV', 'Futrono'),
        (286, 'XIV', 'La Unión'),
        (287, 'XIV', 'Lago Ranco'),
        (288, 'XIV', 'Lanco'),
        (289, 'XIV', 'Los Lagos'),
        (290, 'XIV', 'Máfil'),
        (291, 'XIV', 'Mariquina'),
        (292, 'XIV', 'Paillaco'),
        (293, 'XIV', 'Panguipulli'),
        (294, 'XIV', 'Río Bueno'),
        -- ── X Los Lagos (295-324) ────────────────────────────────────────
        (295, 'X',   'Puerto Montt'),
        (296, 'X',   'Calbuco'),
        (297, 'X',   'Cochamó'),
        (298, 'X',   'Fresia'),
        (299, 'X',   'Frutillar'),
        (300, 'X',   'Los Muermos'),
        (301, 'X',   'Llanquihue'),
        (302, 'X',   'Maullín'),
        (303, 'X',   'Puerto Varas'),
        (304, 'X',   'Castro'),
        (305, 'X',   'Ancud'),
        (306, 'X',   'Chonchi'),
        (307, 'X',   'Curaco de Vélez'),
        (308, 'X',   'Dalcahue'),
        (309, 'X',   'Puqueldón'),
        (310, 'X',   'Queilén'),
        (311, 'X',   'Quellón'),
        (312, 'X',   'Quemchi'),
        (313, 'X',   'Quinchao'),
        (314, 'X',   'Osorno'),
        (315, 'X',   'Puerto Octay'),
        (316, 'X',   'Purranque'),
        (317, 'X',   'Puyehue'),
        (318, 'X',   'Río Negro'),
        (319, 'X',   'San Juan de la Costa'),
        (320, 'X',   'San Pablo'),
        (321, 'X',   'Chaitén'),
        (322, 'X',   'Futaleufú'),
        (323, 'X',   'Hualaihué'),
        (324, 'X',   'Palena'),
        -- ── XI Aysén (325-334) ───────────────────────────────────────────
        (325, 'XI',  'Coyhaique'),
        (326, 'XI',  'Lago Verde'),
        (327, 'XI',  'Aysén'),
        (328, 'XI',  'Cisnes'),
        (329, 'XI',  'Guaitecas'),
        (330, 'XI',  'Chile Chico'),
        (331, 'XI',  'Río Ibáñez'),
        (332, 'XI',  'Cochrane'),
        (333, 'XI',  'O''Higgins'),
        (334, 'XI',  'Tortel'),
        -- ── XII Magallanes (335-345) ─────────────────────────────────────
        (335, 'XII', 'Punta Arenas'),
        (336, 'XII', 'Laguna Blanca'),
        (337, 'XII', 'Río Verde'),
        (338, 'XII', 'San Gregorio'),
        (339, 'XII', 'Cabo de Hornos'),
        (340, 'XII', 'Antártica'),
        (341, 'XII', 'Porvenir'),
        (342, 'XII', 'Primavera'),
        (343, 'XII', 'Timaukel'),
        (344, 'XII', 'Natales'),
        (345, 'XII', 'Torres del Paine')
    ) AS v ([idComuna], [regionCodigo], [Comuna])
    JOIN [dbo].[OPT_Region] r ON r.[Codigo] = v.[regionCodigo] AND r.[IsDeleted] = 0;

    SET IDENTITY_INSERT [dbo].[OPT_Comuna] OFF;

    -- Resincronizar el IDENTITY al valor máximo insertado
    DBCC CHECKIDENT('[dbo].[OPT_Comuna]', RESEED, 345);

    PRINT 'OPT_Comuna: 345 comunas insertadas exitosamente.';
END
GO
